# Generated by Django 5.0.3 on 2024-04-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0004_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='family',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
